export const FETCH_LIST_PRODUCT="FETCH_LIST_PRODUCT";
export const SET_LIST_PRODUCT="SET_LIST_PRODUCT";

export const FETCH_LIST_NEWS="FETCH_LIST_NEWS";
export const SET_LIST_NEWS="SET_LIST_NEWS";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"

export const DELETE_NEWS = "DELETE_NEWS";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_FAIL = "DELETE_NEWS_FAIL"

export const SHOW_BUTTON_DETAIL = "SHOW_BUTTON_DETAIL"
export const HIDDEN_BUTTON_DETAIL = "HIDDEN_BUTTON_DETAIL"

export const ADD_DETAIL_NEWS = "ADD_DETAIL_NEWS";
export const ADD_DETAIL_NEWS_SUCCESS = "ADD_DETAIL_NEWS_SUCCESS";
export const ADD_DETAIL_NEWS_FAIL = "ADD_DETAIL_NEWS_FAIL"